In [64]:
import pandas as pd
import numpy as np

In [72]:
df = pd.read_fwf('Assets/SMSSpamCollection')
df.to_csv('SMSSpamCollection.csv')

In [73]:
spamCollection =  pd.read_csv('Assets/SMSSpamCollection', sep = '\t' , header = None, names=['Label', 'SMS'])
print(spamCollection.shape)
spamCollection.head()

(5572, 2)

  Label                                                SMS
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [74]:
label = list(spamCollection['Label'])
spam = 0 
notSpam = 0
for i in label:
    if i == 'ham':
        notSpam += 1
    else:
        spam+=1
print("Spam:", spam)
print("Not spam:", notSpam)

Spam: 747
Not spam: 4825

<p><b>This dataset is quite reliable as it is reflective of the real world where most messages will not be spam.</b></p> 
<p><b>Let's randomize our data set and split it to train, validation and test dataset!</b></p> 
<p><b>Note that the random state is now 1, train, validation and test in a split of : 80, 10, 10</b></p>

In [75]:
spamCollectionRandom = spamCollection.sample(frac = 1, random_state= 1).reset_index(drop = True)
spamCollectionRandom.head()

  Label                                                SMS
0   ham                       Yep, by the pretty sculpture
1   ham      Yes, princess. Are you going to make me moan?
2   ham                         Welp apparently he retired
3   ham                                            Havent.
4   ham  I forgot 2 ask ü all smth.. There's a card on ...

In [87]:
#splitting into training , validation and test sets 
training_test_index = round(len(spamCollectionRandom) * 0.8)
rest_index = len(spamCollectionRandom) - training_test_index

training_set = spamCollectionRandom[:training_test_index].reset_index(drop=True)
validation_set = spamCollectionRandom[training_test_index:training_test_index+ rest_index//2].reset_index(drop=True)
test_set = spamCollectionRandom[training_test_index + rest_index//2:].reset_index(drop=True)

In [88]:
training_set

     Label                                                SMS
0      ham                       Yep, by the pretty sculpture
1      ham      Yes, princess. Are you going to make me moan?
2      ham                         Welp apparently he retired
3      ham                                            Havent.
4      ham  I forgot 2 ask ü all smth.. There's a card on ...
...    ...                                                ...
4453   ham  Sorry, I'll call later in meeting any thing re...
4454   ham  Babe! I fucking love you too !! You know? Fuck...
4455  spam  U've been selected to stay in 1 of 250 top Bri...
4456   ham  Hello my boytoy ... Geeee I miss you already a...
4457   ham                           Wherre's my boytoy ? :-(

[4458 rows x 2 columns]

In [89]:
validation_set

    Label                                                SMS
0     ham          Later i guess. I needa do mcat study too.
1     ham             But i haf enuff space got like 4 mb...
2    spam  Had your mobile 10 mths? Update to latest Oran...
3     ham  All sounds good. Fingers . Makes it difficult ...
4     ham  All done, all handed in. Don't know if mega sh...
..    ...                                                ...
552   ham  Msgs r not time pass.They silently say that I ...
553   ham  Wot about on wed nite I am 3 then but only til 9!
554   ham  Imagine Life WITHOUT ME... see.. How fast u ar...
555   ham              It‘s reassuring, in this crazy world.
556   ham  Happy or sad , one thing about past is- "Its n...

[557 rows x 2 columns]

In [90]:
test_set

    Label                                                SMS
0     ham  What i told before i tell. Stupid hear after i...
1     ham  I don't know, same thing that's wrong everyso ...
2     ham  Hope you are having a good week. Just checking in
3     ham                K:)i will give my kvb acc details:)
4     ham                           Hi..i got the money da:)
..    ...                                                ...
552   ham  We're all getting worried over here, derek and...
553   ham  Oh oh... Den muz change plan liao... Go back h...
554   ham  CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C...
555  spam  Text & meet someone sexy today. U can find a d...
556   ham                            K k:) sms chat with me.

[557 rows x 2 columns]

<h2>Here we need to choose our dictionary, we need to featurize it:</h2>
<ul>
<li>Tokenization- produce a list out of the raw message.</li>
<li>Stop Word removal- words that don't mean much: that, this, I.</li>
<li>Non-alphabetic removal- as the name suggests.</li>
<li>Stemming or Lemmatization - since this is just a simple project, I will use stemming instead.</li>
<li>Lowercasing</li>
</ul>